config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index', via: :get

  resources :products, only: ['index', 'show'] do
    post '/reorder', to: 'products#reorder'
    post '/subscribe', to: 'products#subscribe'
    delete '/unsubscribe', to: 'products#unsubscribe'
  end
  
  resources :subscriptions, only: [:show, :index, :destroy]
  resources :subscription_items, only: [:destroy]
  resources :orders, only: [:index, :destroy]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :orders, only: [] do 
        collection do
          post 'create', to: 'orders#create'
        end
      end
    end
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  include SubscriptionStatus
  
  # Accessor to simplify access to category on creating the object
  attr_accessor :category

  belongs_to :customer
  has_many :subscription_items
  has_many :products, through: :subscription_items
  has_many :orders, through: :subscription_items

  enum status: STATUS

  validates :customer, presence: true

  
  scope :by_category, ->(category_id) {joins(:products).where(products: {category_id: category_id})}
  scope :by_customer, ->(customer_id) {where(customer_id: customer_id)}

  after_commit :create_subscription_on_payment_gateway, on: :create

  after_update :cancel_subscription_items, if: proc {status_changed? && canceled?}
  validate :uniqueness_by_category
  

  def create_subscription_on_payment_gateway
    # Set the job to be performed after 6h, this way the user can cancel the
    # subscription if wanted
    # It's set to 1.minute for the sake of the tests
    SubscribeJob.perform_in(1.minute.to_i, self.id)
  end

  def cancel_subscription_on_payment_gateway
    PaymentGateway::Subscription.cancel(self.stripe_id)
  end

  def cancel_subscription
    if self.stripe_id.present? 
      return false if self.cancel_subscription_on_payment_gateway.nil?
    end
    self.update_attributes(status: STATUS[:canceled])
    true
  end

  def cancel_subscription_items
    self.subscription_items.each {|si| si.update_attributes(status: STATUS[:canceled])}
  end

  def uniqueness_by_category
    #uses accessor to get category passed when object is built
    category = self.category
    customer = self.customer_id
    if Subscription.available.by_customer(customer).by_category(category).present?
      errors[:base] << I18n.t('subscriptions.errors.is_not_unique')
    end
  end

  def add_to_subscription(product)
    extra_item = self.active?
    if self.subscription_items.available.exists?(product_id: product.id)
      errors[:base] << I18n.t('subscriptions.errors.plan_is_not_unique')
      return false
    else
      self.subscription_items.create(product_id: product.id, extra_item: extra_item)
    end
  end

  def get_category
    self.products.first.category
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  
  before_action :set_current_user
  
  def index
    @subscriptions = @current_user.subscriptions.order(id: :desc)
  end

  def show
    @subscription = @current_user.subscriptions.find(params[:id])
    @subscription_items = @subscription.subscription_items
    @orders = @subscription.orders
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    respond_to do |format|
      if @subscription.cancel_subscription
        format.html { redirect_to subscriptions_url, notice: I18n.t('subscriptions.canceled') }
      else
        flash[:error] =  I18n.t('subscriptions.errors.cancel')
        format.html { redirect_to subscriptions_url }
      end
    end
  end
end

app/views/subscriptions/_orders_info.html.erb
<% if @orders.any? %>
  <div id='plans_info'>
    <h4>Orders in this subscription:</h4>
    <table id='subscriptions'>
      <tr id='header'>
        <th> Id </th>
        <th> Product </th>
        <th> Price </th>
        <th> Created At </th>
      </tr>
      <% @orders.each do |order| %>
        <tr>
          <td> <%= order.id %> </td>
          <td> <%= order.subscription_item.product.name %> </td>
          <td> <%= order.price %> </td>
          <td> <%= order.created_at %> </td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/subscriptions/_plans_info.html.erb
<div id='plans_info'>
  <h4>Products in this subscription:</h4>
  <table id='subscriptions'>
    <tr id='header'>
      <th> Id </th>
      <th> Category </th>
      <th> Product </th>
      <th> Status </th>
      <th> Subscribed At </th>
      <th> Actions </th>
    </tr>
    <% @subscription_items.each do |si| %>
      <tr>
        <td> <%= si.id %> </td>
        <td> <%= si.product.category.name %> </td>
        <td> <%= si.product.name %> </td>
        <td> <%= si.status %> </td>
        <td> <%= si.created_at %> </td>
        <td>
          <%= button_to 'Unsubscribe', si, method: :delete if si.available? %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/subscriptions/_subscription.html.erb
<div id='subscription_info'>
  <div>
    <label> ID: </label>
    <b><%= @subscription.id %></b>
  </div>
  <div>
    <label> Category: </label>
    <b><%= @subscription.get_category.name %></b>
  </div>
  <div>
    <label> Status: </label>
    <b><%= @subscription.status %></b>
  </div>
  <div>
    <label> Created At: </label>
    <b><%= @subscription.created_at.strftime('%m/%d/%Y %H:%M:%S') %></b>
  </div>
</div>

app/views/subscriptions/index.html.erb
<h3>My subscriptions: </h3>
<table id='subscriptions'>
  <tr id='header'>
    <th> Id </th>
    <th> Category </th>
    <th> Status </th>
    <th> Subscribed At </th>
    <th> Products </th>
    <th> Actions </th>
  </tr>
  <% @subscriptions.each do |subscription| %>
    <tr>
      <td><b><%= subscription.id %></b></td>
      <td><b><%= subscription.get_category.name %></b></td>
      <td><b><%= subscription.status %></b></td>
      <td><b><%= subscription.created_at.strftime('%m/%d/%Y %H:%M:%S') %></b></td>
      <td>
        <%= subscription.subscription_items.map {|si| si.product.name }.join(', ') %>
      </td>
      <td>
        <%= button_to 'Unsubscribe', subscription, method: :delete if subscription.available? %>
        <%= button_to 'View', subscription_path(subscription.id), method: :get %>
      </td>
    </tr>
  <% end %>
</table>

app/views/subscriptions/show.html.erb
<h3> Subscription for <%= @subscription.get_category.name %></h3>

<%= render partial: 'subscription' %>

<%= render partial: 'plans_info' %>

<%= render partial: 'orders_info' %>